/**
 * Generated by `npm run places:media` / rebuild-place-media-from-disk.
 * Do not edit by hand — re-run the script to refresh.
 */
import type {
  PlaceGalleryImage,
  PlaceMenuSection,
  PlaceVideo,
} from "./place-types";

export type PlaceMediaBundle = {
  image?: string;
  gallery?: readonly PlaceGalleryImage[];
  menu?: readonly PlaceMenuSection[];
  menuUrl?: string;
  videos?: readonly PlaceVideo[];
  googlePlaceId?: string;
  phone?: string;
  geo?: { lat: number; lng: number };
};

export const placeMediaById: Record<string, PlaceMediaBundle> = {
  "boho": {
      "image": "/places/boho/official-1.jpg",
      "gallery": [
          {
              "src": "/places/boho/official-1.jpg",
              "alt": "boho photo 1",
              "source": "official"
          },
          {
              "src": "/places/boho/official-2.png",
              "alt": "boho photo 2",
              "source": "official"
          },
          {
              "src": "/places/boho/official-3.jpg",
              "alt": "boho photo 3",
              "source": "official"
          },
          {
              "src": "/places/boho/official-4.jpg",
              "alt": "boho photo 4",
              "source": "official"
          },
          {
              "src": "/places/boho/official-5.jpg",
              "alt": "boho photo 5",
              "source": "official"
          },
          {
              "src": "/places/boho/official-6.jpeg",
              "alt": "boho photo 6",
              "source": "official"
          },
          {
              "src": "/places/boho/official-7.jpg",
              "alt": "boho photo 7",
              "source": "official"
          },
          {
              "src": "/places/boho/official-8.jpg",
              "alt": "boho photo 8",
              "source": "official"
          }
      ]
  },
  "brioche": {
      "image": "/places/brioche/official-1.png",
      "gallery": [
          {
              "src": "/places/brioche/official-1.png",
              "alt": "brioche photo 1",
              "source": "official"
          },
          {
              "src": "/places/brioche/official-2.png",
              "alt": "brioche photo 2",
              "source": "official"
          },
          {
              "src": "/places/brioche/official-3.png",
              "alt": "brioche photo 3",
              "source": "official"
          },
          {
              "src": "/places/brioche/official-4.png",
              "alt": "brioche photo 4",
              "source": "official"
          },
          {
              "src": "/places/brioche/official-5.png",
              "alt": "brioche photo 5",
              "source": "official"
          },
          {
              "src": "/places/brioche/official-6.png",
              "alt": "brioche photo 6",
              "source": "official"
          },
          {
              "src": "/places/brioche/official-7.png",
              "alt": "brioche photo 7",
              "source": "official"
          },
          {
              "src": "/places/brioche/official-8.png",
              "alt": "brioche photo 8",
              "source": "official"
          }
      ]
  },
  "casa-verde": {
      "image": "/places/casa-verde/official-1.jpg",
      "gallery": [
          {
              "src": "/places/casa-verde/official-1.jpg",
              "alt": "casa verde photo 1",
              "source": "official"
          },
          {
              "src": "/places/casa-verde/official-1.png",
              "alt": "casa verde photo 2",
              "source": "official"
          },
          {
              "src": "/places/casa-verde/official-2.webp",
              "alt": "casa verde photo 3",
              "source": "official"
          },
          {
              "src": "/places/casa-verde/official-3.webp",
              "alt": "casa verde photo 4",
              "source": "official"
          },
          {
              "src": "/places/casa-verde/official-4.webp",
              "alt": "casa verde photo 5",
              "source": "official"
          },
          {
              "src": "/places/casa-verde/official-5.webp",
              "alt": "casa verde photo 6",
              "source": "official"
          },
          {
              "src": "/places/casa-verde/official-6.jpg",
              "alt": "casa verde photo 7",
              "source": "official"
          },
          {
              "src": "/places/casa-verde/official-7.png",
              "alt": "casa verde photo 8",
              "source": "official"
          }
      ],
      "menuUrl": "https://casaverde.rw/menu"
  },
  "chess-cafe": {
      "image": "/places/chess-cafe/official-2.jpg",
      "gallery": [
          {
              "src": "/places/chess-cafe/official-2.jpg",
              "alt": "chess cafe photo 1",
              "source": "official"
          },
          {
              "src": "/places/chess-cafe/official-3.jpg",
              "alt": "chess cafe photo 2",
              "source": "official"
          },
          {
              "src": "/places/chess-cafe/official-4.jpg",
              "alt": "chess cafe photo 3",
              "source": "official"
          },
          {
              "src": "/places/chess-cafe/official-5.jpg",
              "alt": "chess cafe photo 4",
              "source": "official"
          }
      ]
  },
  "chomad": {
      "image": "/places/chomad/official-3.jpg",
      "gallery": [
          {
              "src": "/places/chomad/official-3.jpg",
              "alt": "chomad photo 1",
              "source": "official"
          }
      ]
  },
  "choose-kigali": {
      "image": "/places/choose-kigali/official-1.jpg",
      "gallery": [
          {
              "src": "/places/choose-kigali/official-1.jpg",
              "alt": "choose kigali photo 1",
              "source": "official"
          },
          {
              "src": "/places/choose-kigali/official-10.jpg",
              "alt": "choose kigali photo 2",
              "source": "official"
          },
          {
              "src": "/places/choose-kigali/official-2.jpg",
              "alt": "choose kigali photo 3",
              "source": "official"
          },
          {
              "src": "/places/choose-kigali/official-3.jpg",
              "alt": "choose kigali photo 4",
              "source": "official"
          },
          {
              "src": "/places/choose-kigali/official-4.jpg",
              "alt": "choose kigali photo 5",
              "source": "official"
          },
          {
              "src": "/places/choose-kigali/official-5.jpg",
              "alt": "choose kigali photo 6",
              "source": "official"
          },
          {
              "src": "/places/choose-kigali/official-6.jpg",
              "alt": "choose kigali photo 7",
              "source": "official"
          },
          {
              "src": "/places/choose-kigali/official-7.jpg",
              "alt": "choose kigali photo 8",
              "source": "official"
          },
          {
              "src": "/places/choose-kigali/official-8.jpg",
              "alt": "choose kigali photo 9",
              "source": "official"
          },
          {
              "src": "/places/choose-kigali/official-9.jpg",
              "alt": "choose kigali photo 10",
              "source": "official"
          }
      ],
      "videos": [
          {
              "type": "youtube",
              "src": "xMGhFbQP-z0",
              "title": "Choose Kigali video",
              "source": "youtube"
          }
      ]
  },
  "fayrouz": {
      "image": "/places/fayrouz/official-1.jpg",
      "gallery": [
          {
              "src": "/places/fayrouz/official-1.jpg",
              "alt": "fayrouz photo 1",
              "source": "official"
          },
          {
              "src": "/places/fayrouz/official-2.jpg",
              "alt": "fayrouz photo 2",
              "source": "official"
          }
      ]
  },
  "habesha": {
      "image": "/places/habesha/official-2.jpg",
      "gallery": [
          {
              "src": "/places/habesha/official-2.jpg",
              "alt": "habesha photo 1",
              "source": "official"
          },
          {
              "src": "/places/habesha/official-3.jpg",
              "alt": "habesha photo 2",
              "source": "official"
          },
          {
              "src": "/places/habesha/official-4.jpg",
              "alt": "habesha photo 3",
              "source": "official"
          },
          {
              "src": "/places/habesha/official-5.jpg",
              "alt": "habesha photo 4",
              "source": "official"
          }
      ]
  },
  "heaven": {
      "image": "/places/heaven/official-1.jpg",
      "gallery": [
          {
              "src": "/places/heaven/official-1.jpg",
              "alt": "heaven photo 1",
              "source": "official"
          },
          {
              "src": "/places/heaven/official-2.jpg",
              "alt": "heaven photo 2",
              "source": "official"
          },
          {
              "src": "/places/heaven/official-3.jpg",
              "alt": "heaven photo 3",
              "source": "official"
          },
          {
              "src": "/places/heaven/official-4.jpg",
              "alt": "heaven photo 4",
              "source": "official"
          },
          {
              "src": "/places/heaven/official-5.png",
              "alt": "heaven photo 5",
              "source": "official"
          },
          {
              "src": "/places/heaven/official-6.jpg",
              "alt": "heaven photo 6",
              "source": "official"
          }
      ]
  },
  "inzora": {
      "image": "/places/inzora/official-1.jpg",
      "gallery": [
          {
              "src": "/places/inzora/official-1.jpg",
              "alt": "inzora photo 1",
              "source": "official"
          },
          {
              "src": "/places/inzora/official-4.jpg",
              "alt": "inzora photo 2",
              "source": "official"
          },
          {
              "src": "/places/inzora/official-5.jpg",
              "alt": "inzora photo 3",
              "source": "official"
          },
          {
              "src": "/places/inzora/official-6.jpg",
              "alt": "inzora photo 4",
              "source": "official"
          },
          {
              "src": "/places/inzora/official-7.jpg",
              "alt": "inzora photo 5",
              "source": "official"
          },
          {
              "src": "/places/inzora/official-8.jpg",
              "alt": "inzora photo 6",
              "source": "official"
          }
      ]
  },
  "le-youkounkoun": {
      "image": "/places/le-youkounkoun/official-10.jpg",
      "gallery": [
          {
              "src": "/places/le-youkounkoun/official-10.jpg",
              "alt": "le youkounkoun photo 1",
              "source": "official"
          },
          {
              "src": "/places/le-youkounkoun/official-3.jpg",
              "alt": "le youkounkoun photo 2",
              "source": "official"
          },
          {
              "src": "/places/le-youkounkoun/official-4.jpg",
              "alt": "le youkounkoun photo 3",
              "source": "official"
          },
          {
              "src": "/places/le-youkounkoun/official-5.jpg",
              "alt": "le youkounkoun photo 4",
              "source": "official"
          },
          {
              "src": "/places/le-youkounkoun/official-6.jpg",
              "alt": "le youkounkoun photo 5",
              "source": "official"
          },
          {
              "src": "/places/le-youkounkoun/official-7.jpg",
              "alt": "le youkounkoun photo 6",
              "source": "official"
          },
          {
              "src": "/places/le-youkounkoun/official-8.jpg",
              "alt": "le youkounkoun photo 7",
              "source": "official"
          },
          {
              "src": "/places/le-youkounkoun/official-9.jpg",
              "alt": "le youkounkoun photo 8",
              "source": "official"
          }
      ]
  },
  "lilly": {
      "image": "/places/lilly/official-1.png",
      "gallery": [
          {
              "src": "/places/lilly/official-1.png",
              "alt": "lilly photo 1",
              "source": "official"
          }
      ]
  },
  "meze-fresh": {
      "image": "/places/meze-fresh/official-1.jpg",
      "gallery": [
          {
              "src": "/places/meze-fresh/official-1.jpg",
              "alt": "meze fresh photo 1",
              "source": "official"
          },
          {
              "src": "/places/meze-fresh/official-3.jpg",
              "alt": "meze fresh photo 2",
              "source": "official"
          }
      ]
  },
  "nyurah": {
      "image": "/places/nyurah/official-1.webp",
      "gallery": [
          {
              "src": "/places/nyurah/official-1.webp",
              "alt": "nyurah photo 1",
              "source": "official"
          },
          {
              "src": "/places/nyurah/official-10.webp",
              "alt": "nyurah photo 2",
              "source": "official"
          },
          {
              "src": "/places/nyurah/official-3.webp",
              "alt": "nyurah photo 3",
              "source": "official"
          },
          {
              "src": "/places/nyurah/official-4.webp",
              "alt": "nyurah photo 4",
              "source": "official"
          },
          {
              "src": "/places/nyurah/official-6.webp",
              "alt": "nyurah photo 5",
              "source": "official"
          },
          {
              "src": "/places/nyurah/official-8.webp",
              "alt": "nyurah photo 6",
              "source": "official"
          },
          {
              "src": "/places/nyurah/official-9.webp",
              "alt": "nyurah photo 7",
              "source": "official"
          }
      ],
      "menuUrl": "https://www.nyurah.com/menu"
  },
  "pan-afrikan": {
      "image": "/places/pan-afrikan/official-1.jpeg",
      "gallery": [
          {
              "src": "/places/pan-afrikan/official-1.jpeg",
              "alt": "pan afrikan photo 1",
              "source": "official"
          },
          {
              "src": "/places/pan-afrikan/official-2.jpg",
              "alt": "pan afrikan photo 2",
              "source": "official"
          },
          {
              "src": "/places/pan-afrikan/official-3.jpg",
              "alt": "pan afrikan photo 3",
              "source": "official"
          },
          {
              "src": "/places/pan-afrikan/official-4.jpg",
              "alt": "pan afrikan photo 4",
              "source": "official"
          },
          {
              "src": "/places/pan-afrikan/official-5.jpg",
              "alt": "pan afrikan photo 5",
              "source": "official"
          },
          {
              "src": "/places/pan-afrikan/official-6.jpg",
              "alt": "pan afrikan photo 6",
              "source": "official"
          },
          {
              "src": "/places/pan-afrikan/official-7.jpg",
              "alt": "pan afrikan photo 7",
              "source": "official"
          },
          {
              "src": "/places/pan-afrikan/official-8.jpg",
              "alt": "pan afrikan photo 8",
              "source": "official"
          }
      ]
  },
  "peacock-cafe": {
      "image": "/places/peacock-cafe/official-1.jpg",
      "gallery": [
          {
              "src": "/places/peacock-cafe/official-1.jpg",
              "alt": "peacock cafe photo 1",
              "source": "official"
          },
          {
              "src": "/places/peacock-cafe/official-2.jpg",
              "alt": "peacock cafe photo 2",
              "source": "official"
          },
          {
              "src": "/places/peacock-cafe/official-3.jpg",
              "alt": "peacock cafe photo 3",
              "source": "official"
          },
          {
              "src": "/places/peacock-cafe/official-4.jpg",
              "alt": "peacock cafe photo 4",
              "source": "official"
          },
          {
              "src": "/places/peacock-cafe/official-5.jpg",
              "alt": "peacock cafe photo 5",
              "source": "official"
          },
          {
              "src": "/places/peacock-cafe/official-6.png",
              "alt": "peacock cafe photo 6",
              "source": "official"
          },
          {
              "src": "/places/peacock-cafe/official-7.png",
              "alt": "peacock cafe photo 7",
              "source": "official"
          }
      ],
      "menuUrl": "https://peacockgarden.net/menu"
  },
  "pili-pili": {
      "image": "/places/pili-pili/official-1.jpg",
      "gallery": [
          {
              "src": "/places/pili-pili/official-1.jpg",
              "alt": "pili pili photo 1",
              "source": "official"
          },
          {
              "src": "/places/pili-pili/official-10.jpg",
              "alt": "pili pili photo 2",
              "source": "official"
          },
          {
              "src": "/places/pili-pili/official-2.jpg",
              "alt": "pili pili photo 3",
              "source": "official"
          },
          {
              "src": "/places/pili-pili/official-3.jpg",
              "alt": "pili pili photo 4",
              "source": "official"
          },
          {
              "src": "/places/pili-pili/official-4.jpg",
              "alt": "pili pili photo 5",
              "source": "official"
          },
          {
              "src": "/places/pili-pili/official-5.jpg",
              "alt": "pili pili photo 6",
              "source": "official"
          },
          {
              "src": "/places/pili-pili/official-6.jpg",
              "alt": "pili pili photo 7",
              "source": "official"
          },
          {
              "src": "/places/pili-pili/official-7.jpg",
              "alt": "pili pili photo 8",
              "source": "official"
          },
          {
              "src": "/places/pili-pili/official-8.png",
              "alt": "pili pili photo 9",
              "source": "official"
          },
          {
              "src": "/places/pili-pili/official-9.jpg",
              "alt": "pili pili photo 10",
              "source": "official"
          }
      ]
  },
  "poivre-noir": {
      "image": "/places/poivre-noir/official-1.jpg",
      "gallery": [
          {
              "src": "/places/poivre-noir/official-1.jpg",
              "alt": "poivre noir photo 1",
              "source": "official"
          }
      ]
  },
  "question-coffee": {
      "image": "/places/question-coffee/official-10.jpg",
      "gallery": [
          {
              "src": "/places/question-coffee/official-10.jpg",
              "alt": "question coffee photo 1",
              "source": "official"
          },
          {
              "src": "/places/question-coffee/official-2.png",
              "alt": "question coffee photo 2",
              "source": "official"
          },
          {
              "src": "/places/question-coffee/official-3.png",
              "alt": "question coffee photo 3",
              "source": "official"
          },
          {
              "src": "/places/question-coffee/official-4.png",
              "alt": "question coffee photo 4",
              "source": "official"
          },
          {
              "src": "/places/question-coffee/official-5.png",
              "alt": "question coffee photo 5",
              "source": "official"
          },
          {
              "src": "/places/question-coffee/official-6.jpg",
              "alt": "question coffee photo 6",
              "source": "official"
          },
          {
              "src": "/places/question-coffee/official-7.jpg",
              "alt": "question coffee photo 7",
              "source": "official"
          },
          {
              "src": "/places/question-coffee/official-8.jpg",
              "alt": "question coffee photo 8",
              "source": "official"
          },
          {
              "src": "/places/question-coffee/official-9.jpg",
              "alt": "question coffee photo 9",
              "source": "official"
          }
      ]
  },
  "repub-lounge": {
      "image": "/places/repub-lounge/official-1.webp",
      "gallery": [
          {
              "src": "/places/repub-lounge/official-1.webp",
              "alt": "repub lounge photo 1",
              "source": "official"
          },
          {
              "src": "/places/repub-lounge/official-10.webp",
              "alt": "repub lounge photo 2",
              "source": "official"
          },
          {
              "src": "/places/repub-lounge/official-2.webp",
              "alt": "repub lounge photo 3",
              "source": "official"
          },
          {
              "src": "/places/repub-lounge/official-3.webp",
              "alt": "repub lounge photo 4",
              "source": "official"
          },
          {
              "src": "/places/repub-lounge/official-4.webp",
              "alt": "repub lounge photo 5",
              "source": "official"
          },
          {
              "src": "/places/repub-lounge/official-5.webp",
              "alt": "repub lounge photo 6",
              "source": "official"
          },
          {
              "src": "/places/repub-lounge/official-6.webp",
              "alt": "repub lounge photo 7",
              "source": "official"
          },
          {
              "src": "/places/repub-lounge/official-7.webp",
              "alt": "repub lounge photo 8",
              "source": "official"
          },
          {
              "src": "/places/repub-lounge/official-8.webp",
              "alt": "repub lounge photo 9",
              "source": "official"
          },
          {
              "src": "/places/repub-lounge/official-9.webp",
              "alt": "repub lounge photo 10",
              "source": "official"
          }
      ],
      "menuUrl": "https://republounge.com/menu"
  },
  "sole-luna": {
      "image": "/places/sole-luna/official-1.jpg",
      "gallery": [
          {
              "src": "/places/sole-luna/official-1.jpg",
              "alt": "sole luna photo 1",
              "source": "official"
          },
          {
              "src": "/places/sole-luna/official-10.jpg",
              "alt": "sole luna photo 2",
              "source": "official"
          },
          {
              "src": "/places/sole-luna/official-11.jpg",
              "alt": "sole luna photo 3",
              "source": "official"
          },
          {
              "src": "/places/sole-luna/official-12.jpg",
              "alt": "sole luna photo 4",
              "source": "official"
          },
          {
              "src": "/places/sole-luna/official-13.jpg",
              "alt": "sole luna photo 5",
              "source": "official"
          },
          {
              "src": "/places/sole-luna/official-14.jpg",
              "alt": "sole luna photo 6",
              "source": "official"
          },
          {
              "src": "/places/sole-luna/official-15.jpg",
              "alt": "sole luna photo 7",
              "source": "official"
          },
          {
              "src": "/places/sole-luna/official-16.jpg",
              "alt": "sole luna photo 8",
              "source": "official"
          },
          {
              "src": "/places/sole-luna/official-2.jpg",
              "alt": "sole luna photo 9",
              "source": "official"
          },
          {
              "src": "/places/sole-luna/official-3.jpg",
              "alt": "sole luna photo 10",
              "source": "official"
          },
          {
              "src": "/places/sole-luna/official-4.jpg",
              "alt": "sole luna photo 11",
              "source": "official"
          },
          {
              "src": "/places/sole-luna/official-5.jpg",
              "alt": "sole luna photo 12",
              "source": "official"
          },
          {
              "src": "/places/sole-luna/official-6.jpg",
              "alt": "sole luna photo 13",
              "source": "official"
          },
          {
              "src": "/places/sole-luna/official-6.png",
              "alt": "sole luna photo 14",
              "source": "official"
          },
          {
              "src": "/places/sole-luna/official-7.jpg",
              "alt": "sole luna photo 15",
              "source": "official"
          },
          {
              "src": "/places/sole-luna/official-8.jpg",
              "alt": "sole luna photo 16",
              "source": "official"
          },
          {
              "src": "/places/sole-luna/official-9.jpg",
              "alt": "sole luna photo 17",
              "source": "official"
          }
      ]
  },
  "yt-burger": {
      "image": "/places/yt-burger/official-1.png",
      "gallery": [
          {
              "src": "/places/yt-burger/official-1.png",
              "alt": "yt burger photo 1",
              "source": "official"
          },
          {
              "src": "/places/yt-burger/official-10.jpg",
              "alt": "yt burger photo 2",
              "source": "official"
          },
          {
              "src": "/places/yt-burger/official-2.png",
              "alt": "yt burger photo 3",
              "source": "official"
          },
          {
              "src": "/places/yt-burger/official-3.jpg",
              "alt": "yt burger photo 4",
              "source": "official"
          },
          {
              "src": "/places/yt-burger/official-3.png",
              "alt": "yt burger photo 5",
              "source": "official"
          },
          {
              "src": "/places/yt-burger/official-4.jpg",
              "alt": "yt burger photo 6",
              "source": "official"
          },
          {
              "src": "/places/yt-burger/official-4.png",
              "alt": "yt burger photo 7",
              "source": "official"
          },
          {
              "src": "/places/yt-burger/official-5.jpg",
              "alt": "yt burger photo 8",
              "source": "official"
          },
          {
              "src": "/places/yt-burger/official-5.png",
              "alt": "yt burger photo 9",
              "source": "official"
          },
          {
              "src": "/places/yt-burger/official-6.jpg",
              "alt": "yt burger photo 10",
              "source": "official"
          },
          {
              "src": "/places/yt-burger/official-6.png",
              "alt": "yt burger photo 11",
              "source": "official"
          },
          {
              "src": "/places/yt-burger/official-7.jpg",
              "alt": "yt burger photo 12",
              "source": "official"
          },
          {
              "src": "/places/yt-burger/official-7.png",
              "alt": "yt burger photo 13",
              "source": "official"
          },
          {
              "src": "/places/yt-burger/official-8.jpg",
              "alt": "yt burger photo 14",
              "source": "official"
          },
          {
              "src": "/places/yt-burger/official-8.png",
              "alt": "yt burger photo 15",
              "source": "official"
          },
          {
              "src": "/places/yt-burger/official-9.jpg",
              "alt": "yt burger photo 16",
              "source": "official"
          }
      ],
      "menuUrl": "https://www.ytburger.com/#menu"
  },
};
